#!/bin/bash

if [ $# == 1 ]; then
	user="admin" # or $USER
	pass="maxwit"
	dbname=$1
elif [ $# == 3 ]; then
	user=$1
	pass=$2
	dbname=$3
else
	echo -e "Usage: $0 [user] [password] <dbname>\n"
	exit 1
fi

os=`uname -s`

case $os in
    'Linux')
        release=`lsb_release -sc`
        if [ "$release" = xenial -o "$release" = Core ]; then
	          mysqlroot="sudo mysql"
        else
	          mysqlroot="mysql -uroot -pmaxwit"
        fi
        ;;
    'Darwin')
	      mysqlroot="mysql -uroot"
        ;;
    *)
        echo "OS '$os' not supported!"
        ;;
esac

dbms=(${0//-/ })
dbms=${dbms[1]}
#host='localhost'

tmp=$(mktemp).sql

case $dbms in
	mysql|mariadb)
# FIXME
# create user IF NOT EXISTS $user identified by '$pass';
	$mysqlroot -e "drop database if exists $dbname; create database $dbname character set=utf8; grant all on $dbname.* to $user@'localhost' identified by '$pass'"

	echo "status" | mysql -u$user -p$pass -D$dbname
	;;

	psql|pgsql|postgresql)
	psql -Upostgres -c "drop database $dbname"

	psql -Upostgres -c "create user $user with password '$pass'"
	psql -Upostgres -c "create database $dbname encoding='utf8' owner=$user"

	echo '----------------------'
	psql -U$user -d$dbname -c "\conninfo"
	psql -U$user -d$dbname -c "\encoding"
	;;

	*)
	echo "$dbms not supported yet!"
	exit 1
	;;
esac

echo
