#!/usr/bin/env bash
set -e

if [ $# == 1 ]; then
	user="admin" # or $USER
	pass="maxwit"
	dbname=$1
elif [ $# == 3 ]; then
	user=$1
	pass=$2
	dbname=$3
else
	echo -e "Usage: $0 [user] [password] <dbname>\n"
	exit 1
fi

os=`uname -s`

case $os in
    'Linux')
		# FIXME
        if [ $UID -eq 0 ]; then
	          mysql_root="mysql"
		else
	          mysql_root="sudo mysql"
		fi
	    # mysql_root="mysql -h127.0.0.1 -uroot -pmaxwit"
        ;;
    'Darwin')
	      mysql_root="mysql -h127.0.0.1 -uroot"
        ;;
    *)
        echo "OS '$os' not supported!"
        ;;
esac

mysql_root="$mysql_root -e"
pgsql_root="psql -Upostgres -c"

dbms=(${0//-/ })
dbms=${dbms[1]}

case $dbms in
	mysql|mariadb)
		$mysql_root "drop user if exists $user"
		$mysql_root "create user $user identified by '$pass'";
		$mysql_root "drop database if exists $dbname"
		$mysql_root "create database $dbname character set=utf8"
		$mysql_root "grant all on $dbname.* to $user@'%'"

		mysql -h127.0.0.1 -u$user -p$pass -D$dbname -e "status"
		;;

	psql|pgsql|postgresql)
		# FIXME
		$pgsql_root "drop database $dbname"

		$pgsql_root "create user $user with password '$pass'"
		$pgsql_root "create database $dbname encoding='utf8' owner=$user"

		echo '----------------------'
		psql -U$user -d$dbname -c "\conninfo"
		psql -U$user -d$dbname -c "\encoding"
		;;

	*)
		echo "$dbms not supported yet!"
		exit 1
		;;
esac

echo
