#!/bin/sh

over=11

if [ $UID != 0 ]; then
	echo  "must run as root!"
	echo
	exit 1
fi

if [ $# = 1 ]; then
	over=$1
fi

user=ora$over

yum install -y compat-libcap1 compat-libstdc++-33 gcc gcc-c++ glibc glibc-devel ksh libgcc libstdc++ libstdc++-devel libaio libaio-devel libXext libXtst libX11 libXau libxcb libXi make sysstat pam xorg-x11-xauth unixODBC unixODBC-devel pdksh elfutils-libelf-devel

/usr/sbin/groupadd oinstall
/usr/sbin/groupadd witdba
/usr/sbin/useradd -g oinstall -G witdba,wheel -c "Oracle $over" $user || exit 1

pass="maxwit"
echo -e "$pass\n$pass" | passwd $user

cp envInit /tmp/
sudo -i -u $user /tmp/envInit $over

echo "please re-login as '$user'!"
echo
