CREATE SEQUENCE tbl_teacher_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_TEACHER ALTER COLUMN id SET DEFAULT nextval('tbl_teacher_id_seq'::regclass);

CREATE SEQUENCE tbl_team_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_TEAM ALTER COLUMN id SET DEFAULT nextval('tbl_team_id_seq'::regclass);

CREATE SEQUENCE tbl_course_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_COURSE ALTER COLUMN id SET DEFAULT nextval('tbl_course_id_seq'::regclass);

CREATE SEQUENCE tbl_category_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_CATEGORY ALTER COLUMN id SET DEFAULT nextval('tbl_category_id_seq'::regclass);

CREATE SEQUENCE tbl_user_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_USER ALTER COLUMN id SET DEFAULT nextval('tbl_user_id_seq'::regclass);

CREATE SEQUENCE tbl_suite_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_SUITE ALTER COLUMN id SET DEFAULT nextval('tbl_suite_id_seq'::regclass);

CREATE SEQUENCE tbl_education_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_EDUCATION ALTER COLUMN id SET DEFAULT nextval('tbl_education_id_seq'::regclass);

CREATE SEQUENCE tbl_history_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_HISTORY ALTER COLUMN id SET DEFAULT nextval('tbl_history_id_seq'::regclass);

CREATE SEQUENCE tbl_lesson_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_LESSON ALTER COLUMN id SET DEFAULT nextval('tbl_lesson_id_seq'::regclass);

CREATE SEQUENCE tbl_project_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_PROJECT ALTER COLUMN id SET DEFAULT nextval('tbl_project_id_seq'::regclass);

CREATE SEQUENCE tbl_work_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;
ALTER TABLE TBL_WORK ALTER COLUMN id SET DEFAULT nextval('tbl_work_id_seq'::regclass);
