ALTER TABLE TBL_TEAM 
ADD CONSTRAINT fk_TBL_TEAM_1  FOREIGN KEY (teacher_id)
  REFERENCES TBL_TEACHER (id) MATCH SIMPLE 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TBL_COURSE_CATEGORY 
ADD CONSTRAINT fk_ackou6yntkyloflc8hpui99g6 FOREIGN KEY (category_id)
      REFERENCES TBL_CATEGORY (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TBL_COURSE_CATEGORY 
ADD CONSTRAINT fk_i725a3n8ljd6rghrk2fx71ivp FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_USER 
ADD CONSTRAINT fk_i5py5jfeds75pefhj87buorbw FOREIGN KEY (team_id)
      REFERENCES TBL_TEAM (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_ADMIN 
ADD CONSTRAINT fk_gal4rh6ct9sc7itpke11ybuos FOREIGN KEY (id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_APPLIED 
ADD CONSTRAINT fk_5hxkk6uox604tmas2kr9q4y7t FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_APPLIED 
ADD CONSTRAINT fk_i3e0j5732ugkwg6gv1d7ygaof FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_BUDDY 
ADD CONSTRAINT fk_39ubf1ntuhj7gw7hovgfdkf79 FOREIGN KEY (i_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_BUDDY 
ADD  CONSTRAINT fk_n4u5o00cm0i1iu2tm9baran8l FOREIGN KEY (u_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_DEPEND
ADD CONSTRAINT fk_b8qty4abdxjlmsqa2vfii36u6 FOREIGN KEY (source_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TBL_COURSE_DEPEND 
ADD CONSTRAINT fk_c3aokeroceyivgomcom0nsv75 FOREIGN KEY (depend_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_IMPROVE 
ADD CONSTRAINT fk_2kccshteina5ln38r4lqka4j0 FOREIGN KEY (improve_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_IMPROVE 
ADD CONSTRAINT fk_r33qewxukuy94cd2urg9bqq5p FOREIGN KEY (source_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_SUITE 
ADD CONSTRAINT fk_6pk67wlv1wi9cgsx29u3m6fh9 FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_SUITE 
ADD CONSTRAINT fk_gc9qjgjukqhr449pmem6gbhxp FOREIGN KEY (suite_id)
      REFERENCES TBL_SUITE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_TEACHER 
ADD CONSTRAINT fk_mw1vc6w3eqt5ep6amevheb6wu FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_TEACHER 
ADD CONSTRAINT fk_bo7oq6hx2tewh6mqlfpuunr7f FOREIGN KEY (teacher_id)
      REFERENCES TBL_TEACHER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_EDUCATION 
ADD CONSTRAINT fk_k97iqi5i4p328n36tvyyewpmi FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_HISTORY 
ADD CONSTRAINT fk_bplvrd5hxrbxx60r1vrdlamt9 FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_LESSON 
ADD CONSTRAINT fk_34htrinpixb0o5afhnnruoiv8 FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_PROJECT 
ADD CONSTRAINT fk_n2v56k12s5rtn2wkcfbtftoyx FOREIGN KEY (teacher_id)
      REFERENCES TBL_TEACHER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_WORK 
ADD CONSTRAINT fk_4vf5gf9pq7eysm0ib42l1ts20 FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;






























