ALTER TABLE TBL_TEAM 
ADD CONSTRAINT fk_teacher_id FOREIGN KEY (teacher_id)
  REFERENCES TBL_TEACHER (id) MATCH SIMPLE 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TBL_COURSE_CATEGORY 
ADD CONSTRAINT fk_category_id FOREIGN KEY (category_id)
      REFERENCES TBL_CATEGORY (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TBL_COURSE_CATEGORY 
ADD CONSTRAINT fk_course_id FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_USER 
ADD CONSTRAINT fk_team_id FOREIGN KEY (team_id)
      REFERENCES TBL_TEAM (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_ADMIN 
ADD CONSTRAINT fk_id FOREIGN KEY (id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_APPLIED 
ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_APPLIED 
ADD CONSTRAINT fk_course_id FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_BUDDY 
ADD CONSTRAINT fk_i_id FOREIGN KEY (i_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_BUDDY 
ADD  CONSTRAINT fk_u_id FOREIGN KEY (u_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE 
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_DEPEND
ADD CONSTRAINT fk_source_id FOREIGN KEY (source_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TBL_COURSE_DEPEND 
ADD CONSTRAINT fk_depend_id FOREIGN KEY (depend_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_IMPROVE 
ADD CONSTRAINT fk_improve_id FOREIGN KEY (improve_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_IMPROVE 
ADD CONSTRAINT fk_source_id FOREIGN KEY (source_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_SUITE 
ADD CONSTRAINT fk_course_id FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_SUITE 
ADD CONSTRAINT fk_suite_id FOREIGN KEY (suite_id)
      REFERENCES TBL_SUITE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_TEACHER 
ADD CONSTRAINT fk_course_id FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_COURSE_TEACHER 
ADD CONSTRAINT fk_teacher_id FOREIGN KEY (teacher_id)
      REFERENCES TBL_TEACHER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_EDUCATION 
ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_HISTORY 
ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_LESSON 
ADD CONSTRAINT fk_course_id FOREIGN KEY (course_id)
      REFERENCES TBL_COURSE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_PROJECT 
ADD CONSTRAINT fk_teacher_id FOREIGN KEY (teacher_id)
      REFERENCES TBL_TEACHER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TBL_WORK 
ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id)
      REFERENCES TBL_USER (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;






























