ALTER TABLE TBL_TEACHER 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_TEAM 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_COURSE 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_CATEGORY 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_USER 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_SUITE 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_EDUCATION 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_HISTORY 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_LESSON 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_PROJECT 
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE TBL_WORK
	CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT ;
