#!/bin/sh

if [ $# != 1 ]; then
	echo "usage: $0 <dbms>"
	exit 1
fi

dbms=$1
out="/tmp/${dbms}"
mkdir -p $out

case $dbms in
mysql)
	pk="integer auto_increment"
	;;
pgsql|postgresql)
	pk="serial"
	;;
mssql|sqlserver)
	pk="integer identity"
	echo 'SET IDENTITY_INSERT TBL_CATEGORY ON;' > $out/insert.sql
	;;
oracle)
	pk="integer"
	;;
*)
	echo "'$dbms' not supported"
	exit 1
esac

sed "s/__PRIMARY_KEY__/$pk/" witweb/create.sql > $out/create.sql
cat witweb/insert.sql >> $out/insert.sql
echo "$out generated"
echo
